version: '3.8'

services:
  geoprompt-db:
    image: postgis/postgis:15-3.3 # PostGIS extension එක දැනටමත් සෙට් කරපු official image එකක්
    container_name: geoprompt_postgres
    restart: always
    environment:
      POSTGRES_USER: geoprompt_user
      POSTGRES_PASSWORD: geoprompt_password
      POSTGRES_DB: geoprompt_navigator_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: